apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: cnj-hello-backend-spring-pdb
  namespace: cxp-team-cloudbirds
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: cnj-hello-backend-spring

